<?php

/**
 * BaseShopCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $ShopMains
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getShopMains() Returns the current record's "ShopMains" collection
 * @method ShopCategory        setName()      Sets the current record's "name" value
 * @method ShopCategory        setShopMains() Sets the current record's "ShopMains" collection
 * 
 * @package    shop
 * @subpackage model
 * @author     farrukh
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseShopCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ShopMain as ShopMains', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}