<?php

/**
 * BaseShopMain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $city
 * @property string $type
 * @property string $item_name
 * @property string $img
 * @property string $location
 * @property string $description
 * @property string $token
 * @property boolean $is_activated
 * @property string $email
 * @property string $phone
 * @property timestamp $expires_at
 * @property ShopCategory $ShopCategory
 * 
 * @method integer      getCategoryId()   Returns the current record's "category_id" value
 * @method string       getCity()         Returns the current record's "city" value
 * @method string       getType()         Returns the current record's "type" value
 * @method string       getItemName()     Returns the current record's "item_name" value
 * @method string       getImg()          Returns the current record's "img" value
 * @method string       getLocation()     Returns the current record's "location" value
 * @method string       getDescription()  Returns the current record's "description" value
 * @method string       getToken()        Returns the current record's "token" value
 * @method boolean      getIsActivated()  Returns the current record's "is_activated" value
 * @method string       getEmail()        Returns the current record's "email" value
 * @method string       getPhone()        Returns the current record's "phone" value
 * @method timestamp    getExpiresAt()    Returns the current record's "expires_at" value
 * @method ShopCategory getShopCategory() Returns the current record's "ShopCategory" value
 * @method ShopMain     setCategoryId()   Sets the current record's "category_id" value
 * @method ShopMain     setCity()         Sets the current record's "city" value
 * @method ShopMain     setType()         Sets the current record's "type" value
 * @method ShopMain     setItemName()     Sets the current record's "item_name" value
 * @method ShopMain     setImg()          Sets the current record's "img" value
 * @method ShopMain     setLocation()     Sets the current record's "location" value
 * @method ShopMain     setDescription()  Sets the current record's "description" value
 * @method ShopMain     setToken()        Sets the current record's "token" value
 * @method ShopMain     setIsActivated()  Sets the current record's "is_activated" value
 * @method ShopMain     setEmail()        Sets the current record's "email" value
 * @method ShopMain     setPhone()        Sets the current record's "phone" value
 * @method ShopMain     setExpiresAt()    Sets the current record's "expires_at" value
 * @method ShopMain     setShopCategory() Sets the current record's "ShopCategory" value
 * 
 * @package    shop
 * @subpackage model
 * @author     farrukh
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseShopMain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_main');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('city', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('item_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('img', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '4000',
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('expires_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}