<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $User_category_id
 * @property string $name
 * @property string $email
 * @property string $token
 * @property UserCategory $UserCategory
 * 
 * @method integer      getUserCategoryId()   Returns the current record's "User_category_id" value
 * @method string       getName()             Returns the current record's "name" value
 * @method string       getEmail()            Returns the current record's "email" value
 * @method string       getToken()            Returns the current record's "token" value
 * @method UserCategory getUserCategory()     Returns the current record's "UserCategory" value
 * @method User         setUserCategoryId()   Sets the current record's "User_category_id" value
 * @method User         setName()             Sets the current record's "name" value
 * @method User         setEmail()            Sets the current record's "email" value
 * @method User         setToken()            Sets the current record's "token" value
 * @method User         setUserCategory()     Sets the current record's "UserCategory" value
 * 
 * @package    shop
 * @subpackage model
 * @author     farrukh
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('User_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserCategory', array(
             'local' => 'user_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}