<?php

/**
 * ShopMain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    shop
 * @subpackage model
 * @author     farrukh
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class ShopMain extends BaseShopMain
{
    public function getCitySlug()
    {
        return Shop::slugify($this->getCity());
    }

    public function getTypeSlug()
    {
        return Shop::slugify($this->getType());
    }

    public function getLocationSlug()
    {
        return Shop::slugify($this->getLocation());
    }

    public function save(Doctrine_Connection $conn = null)
    {
        if ($this->isNew() && !$this->getExpiresAt())
        {
            $now = $this->getCreatedAt() ? $this->getDateTimeObject('created_at')->format('U') : time();
            $this->setExpiresAt(date('Y-m-d h:i:s', $now + 86400 * sfConfig::get('app_active_days')));
        }

        return parent::save($conn);
    }
    public function extend($force = false)
    {
        if (!$force && !$this->expiresSoon())
        {
            return false;
        }

        $this->setExpiresAt(date('Y-m-d', time() + 86400 * sfConfig::get('app_active_days')));
        $this->save();

        return true;
    }
}