<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/11/12 04:27:30
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
);
