<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/11/12 04:42:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=shop',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'cp1251',
  'name' => 'doctrine',
)),);
