ShopCategory:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }

ShopMain:
  actAs: { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }
    city:         { type: string(20), notnull: true }
    type:         { type: string(255), notnull: true }
    item_name:    { type: string(255), notnull: true }
    img:          { type: string(255) }
    location:     { type: string(255), notnull: true }
    description:  { type: string(4000), notnull: true }
    token:        { type: string(255), notnull: true, unique: true }
    is_activated: { type: boolean, notnull: true, default: 0 }
    email:        { type: string(255), notnull: true }
    phone:        { type: string(255), notnull: true }
    expires_at:   { type: timestamp, notnull: true }
  relations:
    ShopCategory: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: ShopMains }

UserCategory:
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(255), notnull: true, unique: true }

User:
  actAs: { Timestampable: ~ }
  columns:
    User_category_id:  { type: integer, notnull: true }
    name:      { type: string(255), notnull: true }
    email:     { type: string(255), notnull: true, unique: true }
    token:     { type: string(255), notnull: true }
  relations:
    UserCategory: { onDelete: CASCADE, local: user_category_id, foreign: id, foreignAlias: Users }